project:
  type: book
  output-dir: docs

number-depth: 2

book:
  title: "Capital Without Category"
  author: ["Zhijun He", "Jerry Miao", "Paxton Boyd"]
  date: today
  date-format: full
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true

  sidebar:
    title: "JZP"
    logo: assets/sidebar-logo.png
    collapse-level: 2
    style: docked
    pinned: true
    search: true

  chapters:
    - index.qmd
    - part: "EDA"
      chapters:
        - eda/eda-member1.qmd
        - eda/eda-member2.qmd
        - eda/eda-member3.qmd

  appendices:
    - appx/proposal.qmd
    - appx/case-study.qmd
    - appx/capital_without_category.qmd
    - wa/wa-member1.qmd
    - wa/wa-member2.qmd
    - wa/wa-member3.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    search: true
    css: style/custom.css
    smooth-scroll: true
    code-copy: true
    code-tools: true
    code-fold: true
    page-layout: full
    number-sections: false

execute:
  echo: true
  warning: false
  error: false
  cache: false

editor:
  mode: source
  markdown:
    wrap: sentence
